import { describe, expect, it } from "vitest";
import { sudokuSprint } from "./game";
const players = [{ id: "a", displayName: "Ada" }, { id: "b", displayName: "Ben" }] as const;
const ctx = { roomId: "ROOM1", now: 10 };
type State = ReturnType<typeof sudokuSprint.createInitialState>;
function place(state: State, actor: string, index: number, value: number): State { const result = sudokuSprint.applyCommand(state, { type: "place", row: Math.floor(index / 4), column: index % 4, value }, actor, ctx); if (!result.accepted) throw new Error(result.reason); return result.state; }
function solutionAt(state: State, index: number): number { const value = state.solution[index]; if (value === undefined) throw new Error("Missing solution cell."); return value; }
describe("Sudoku Sprint", () => {
  it("keeps the solution and boards viewer-private", () => { let state = sudokuSprint.createInitialState(players, ctx); const index = state.puzzle.findIndex((value) => value === 0); state = place(state, "a", index, solutionAt(state, index)); const a = sudokuSprint.projectState(state, "a"); const b = sudokuSprint.projectState(state, "b"); expect(a.board[index]).toBe(state.solution[index]); expect(b.board[index]).toBe(0); expect(b.progress.a).toBe(9); expect(b).not.toHaveProperty("playerStates"); expect(b).not.toHaveProperty("solution"); });
  it("generates a valid solution without a fixed answer literal", () => { const state = sudokuSprint.createInitialState(players, ctx); for (let row = 0; row < 4; row += 1) expect(new Set(state.solution.slice(row * 4, row * 4 + 4))).toEqual(new Set([1,2,3,4])); for (let column = 0; column < 4; column += 1) expect(new Set([0,1,2,3].map((row) => state.solution[row * 4 + column]))).toEqual(new Set([1,2,3,4])); });
  it("tracks mistakes and prevents clue or filled-cell changes", () => { let state = sudokuSprint.createInitialState(players, ctx); const index = state.puzzle.findIndex((value) => value === 0); const wrong = solutionAt(state, index) % 4 + 1; state = place(state, "a", index, wrong); expect(state.playerStates.a?.mistakes).toBe(1); const clue = state.puzzle.findIndex((value) => value !== 0); expect(sudokuSprint.applyCommand(state, { type: "place", row: Math.floor(clue / 4), column: clue % 4, value: 2 }, "a", ctx)).toMatchObject({ accepted: false }); state = place(state, "a", index, solutionAt(state, index)); expect(sudokuSprint.applyCommand(state, { type: "place", row: Math.floor(index / 4), column: index % 4, value: wrong }, "a", ctx)).toMatchObject({ accepted: false }); });
  it("ends on the first solved board and derives bounded score", () => { let state = sudokuSprint.createInitialState(players, ctx); for (const [index, value] of state.solution.entries()) if (state.puzzle[index] === 0) state = place(state, "a", index, value); expect(state.winnerId).toBe("a"); expect(sudokuSprint.isComplete?.(state)).toBe(true); expect(sudokuSprint.getScores?.(state)).toEqual({ a: 100, b: 0 }); });
  it("strictly validates bounded commands", () => { expect(sudokuSprint.validateCommand({ type: "place", row: 0, column: 0, value: 1 })).toBe(true); expect(sudokuSprint.validateCommand({ type: "place", row: 4, column: 0, value: 1 })).toBe(false); expect(sudokuSprint.validateCommand({ type: "place", row: 0, column: 0, value: 1, extra: true })).toBe(false); });
});
